name: build adservers.txt

on:
  workflow_dispatch:
  push:
    paths:
      - 'source/top100k.txt'
      - 'source/top100k-white.txt'

permissions:
  contents: write

jobs:
  update-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Run update script
        run: |
          bash scripts/DomainExclusion.sh
          python3 scripts/BuildAdservers.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Update filters"
          add: |
            rules/adservers.txt
            rules/adservers-add.txt
            source/top100k-white.txt
          detect_unchanged: true
          push: true
          fetch: false

      - name: Final cleanup
        if: always()
        run: |
          rm -rf rules/ scripts/ source/