name: Update dragon.txt

on:
  schedule:
    - cron: '20 18 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-dragon:
    runs-on: ubuntu-latest
    
    steps:
      - name: git
        uses: actions/checkout@v4

      - name: conf Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: run dragon_move.py
        run: python3 scripts/dragon_move.py rules/dragon.txt rules/dragon_add.txt rules/dragon_del.txt

      - name: git push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rules/dragon.txt
          if git diff --quiet --cached --exit-code; then
            echo "No changes."
          else
            git commit -m "update: $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push
            echo "push changes."
          fi