name: 2.Build find_dragon.txt

on:
  schedule:
    - cron: '40 18 * * 1'  # every Monday at UTC 18:40 (BeiJing Time 02:40 Tuesday)
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run update script
        run: |
          set -e
          bash scripts/find_dragon.sh

      - name: Final cleanup
        if: always()
        run: |
          rm -rf rules/ scripts/ || true