name: 3.build asservs.txt

on:
  schedule:
    - cron: '50 18 * * 1'  # every Monday at UTC 18:50 (BeiJing Time 02:50 Tuesday)
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run update script
        run: |
          set -e
          bash scripts/find_fish.sh

      - name: Final cleanup
        if: always()
        run: |
          rm -rf rules/ scripts/ || true
