name: fix WhiteDomain

on:
  workflow_dispatch:
  push:
    paths:
      - 'source/whitelist.txt'

permissions:
  contents: write

jobs:
  update-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Run update script
        run: |
          python scripts/fixWhiteDomain.py
          python scripts/generate_adservers.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v10
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          default_author: user_info
          message: "Update filters"
          add: |
            rules/adservers.txt
            rules/week-add.txt
            source/whitebasic-top100k.txt
          pull: '--rebase --autostash'
          push: true
          push_attempts: 3

      - name: Final cleanup
        if: always()
        run: |
          rm -rf rules/ scripts/ source/
