name: test1

on:
  schedule:
#    - cron: '0 18 * * *'  # everyday UTC 18:00（BeiJing Time 02:00）
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run update script
        run: |
          set -e
          bash scripts/test1.sh

      - name: Final cleanup
        if: always()
        run: |
          rm -rf rules/ scripts/ || true
